### ISSUE TITLE
FEAT: keybinding items frame and scroll

### ISSUE THREAD

**Issue by LintaoAmons** [LintaoAmons/Keyboard#10]
![image](https://github.com/LintaoAmons/Keyboard/assets/95092244/30f37a20-4df0-42c8-849d-f94633f3a569)

**Comment by iampaandey** [comment]
Assign this to me ..?

**Comment by LintaoAmons** [comment]
> Assign this to me ..?

Thanks, if you want!

**Comment by iampaandey** [comment]
@LintaoAmons please review ,I have raised a PR for the same.
